[platformio]
default_envs = esp32dev, blackpill_f401cc

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^3.11.0

[env:esp32dev]
platform = espressif32
board = esp32dev
build_src_filter =
  +<esp32/>
  -<stm32/>

[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
build_src_filter =
  +<stm32/>
  -<esp32/>
lib_deps =
  ${env.lib_deps}
  stm32duino/STM32duino FreeRTOS @ ^10.3.2
upload_protocol = dfu
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D USBD_VID=0x0483
  -D USBD_PID=0x5740
